import { Product } from './product';

export const PRODUCTS: Product[] = [
  {
    description: 'This is a large green apple',
    id: 1,
    image_url: 'https://i5.walmartimages.ca/images/Enlarge/094/514/6000200094514.jpg',
    name: 'Apple',
    number_items: 3,
    price: 10,
  },
  {
    description: 'Here we have a round potato',
    id: 2,
    image_url: 'https://target.scene7.com/is/image/Target/GUEST_c58aff39-9071-4f1b-a270-5d00f41a0db4?wid=488&hei=488&fmt=pjpeg',
    name: 'Potato',
    number_items: 2,
    price: 20,
  },
  {
    description: 'There is a yellow small banana',
    id: 3,
    image_url: 'https://thumbs-prod.si-cdn.com/_oO5E4sOE9Ep-qk_kuJ945_-qo4=/800x600/filters:no_upscale()/https://public-media.si-cdn.com/filer/d5/24/d5243019-e0fc-4b3c-8cdb-48e22f38bff2/istock-183380744.jpg',
    name: 'Banana',
    number_items: 3,
    price: 2,
  },
  {
    description: 'This is an apricot',
    id: 4,
    image_url: 'https://cdn.shopify.com/s/files/1/2971/2126/products/Apricot_Kernel_2000x.jpg?v=1571688918',
    name: 'Apricot',
    number_items: 2,
    price: 1,
  },
  {
    description: 'The coconut is on the tree',
    id: 5,
    image_url: 'https://www.np-d.com/media/images/org/shutterstock_211694872_Kokosnussoel_1.jpg',
    name: 'Coconut',
    number_items: 4,
    price: 5,
  },
  {
    description: 'This kiwi is really sweet',
    id: 6,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Kiwi_%28Actinidia_chinensis%29_1_Luc_Viatour.jpg',
    name: 'Kiwi',
    number_items: 10,
    price: 8,
  },
  {
    description: 'The chestnut is hot right now',
    id: 7,
    image_url: 'https://images-na.ssl-images-amazon.com/images/I/51enGoB-rhL._SX466_.jpg',
    name: 'Chestnut',
    number_items: 1,
    price: 40,
  },
  {
    description: 'This carrot is super tasty',
    id: 8,
    image_url: 'https://befreshcorp.net/wp-content/uploads/2017/06/product-packshot-Carrot-558x600.jpg',
    name: 'Carrot',
    number_items: 5,
    price: 3,
  },
  {
    description: 'The biggest strawberry you have ever seen',
    id: 9,
    image_url: 'https://www.totalagrisolutions.com/wp-content/uploads/2019/09/strawberry-1.jpg',
    name: 'Strawberry',
    number_items: 1,
    price: 100,
  },
  {
    description: 'This is a good mellon',
    id: 10,
    image_url: 'https://www.brighthealing.com/wp-content/uploads/Yellow-Melon.jpg',
    name: 'Mellon',
    number_items: 3,
    price: 51,
  },
];
